# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Flashforge Finder API
version: "0.2.2"
slug: fff_api
description: API server for Flashforge Finder
url: "https://github.com/paulsbroomfield/hassio-addons/tree/master/fff_api"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  printer_ip: "192.168.1.15"
schema:
  printer_ip: "str?"
##image: "ghcr.io/home-assistant/{arch}-fff_api"
ports: 
  8899/tcp: 8899
ports_description:
  8899/tcp: "Flask API"